name: Back Merge
description: Merge code back into develop on push to main

inputs:
  src-branch:
    description: 'What branch is acting as the source of the merger'
    required: false
    default: 'main'
  dest-branch:
    description: 'What branch is acting as the destination of the merger'
    required: false
    default: ${{ github.event.repository.default_branch }}
  submodules:
    description: 'Whether to checkout submodules'
    required: false
    default: 'false'
  token:
    description: 'GitHub token'
    required: false
  commit-message:
    description: 'The commit message to use for the merge'
    required: false
  commit-author-name:
    description: 'The author name to use for the merge'
    required: false
    default: 'github-actions'
  commit-author-email:
    description: 'The email to use for the merge'
    required: false
    default: 'github-actions@github.com'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ inputs.token }}
        submodules: ${{ inputs.submodules }}
    - name: Source Branch
      id: src-branch
      run: |
        if [ -n "${{ inputs.src-branch }}" ]; then
          echo "::set-output name=branch::${{ inputs.src-branch }}"
        elif [ "${{ github.event_name }}" = "push" ]; then
          echo "::set-output name=branch::${{ github.ref_name }}"
        else
          echo "::set-output name=branch::main"
        fi
      shell: bash
    - name: Commit Message
      id: message
      run: |
        if [ -n "${{ inputs.commit-message }}" ]; then
          echo "::set-output name=message::$(echo ${{ inputs.commit-message }} | sed 's|\"|\\\"|g')"
        else
          echo "::set-output name=message::Merge branch '${{ steps.src-branch.outputs.branch }}' into '${{ inputs.dest-branch }}'"
        fi
      shell: bash
    - name: Merge
      run: |
        git config user.email ${{ inputs.commit-author-email }}
        git config user.name ${{ inputs.commit-author-name }}
        git fetch
        git checkout ${{ inputs.dest-branch }}
        git merge ${{ inputs.src-branch }} --strategy-option theirs -m "${{ steps.message.outputs.message }}" --allow-unrelated-histories
        git push -u origin ${{ inputs.dest-branch }}
      shell: bash
